#!/bin/bash
app=src/main/java/com/example/App.java
properties=src/main/resources/application.properties

cd ../create-database
sed -i 's/localhost/mysql/' $app
mvn package assembly:single
sed -i 's/mysql/localhost/2' $app
cd -
cp ../create-database/target/create-database-1.0-SNAPSHOT-jar-with-dependencies.jar ./

sed -i 's/localhost/mysql/' $properties
sudo mvn clean
sudo mvn package -DskipTests
sudo mvn clean

rm -rf target

sed -i 's/mysql/localhost/2' $properties

if [ $# -eq 0 ]; then
    exit 0;
fi

if [ $1 == refresh ]; then
    sudo docker compose rm --volumes app
fi

exit 0

